apiVersion: v1
kind: Service
metadata:
  name: llmap-canary-route
spec:
  selector:
    app.kubernetes.io/name: llmap
    app.kubernetes.io/instance: llmap-canary
    rollout.llmap.dev/traffic: candidate
